# Generated by Django 4.1.2 on 2022-11-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='accoount',
            new_name='account',
        ),
    ]
