# Generated by Django 4.1.2 on 2022-11-12 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0020_shippingaddress_phone'),
        ('wishlist', '0002_rename_accoount_wishlist_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj.product'),
        ),
    ]
