# Generated by Django 4.1.2 on 2022-11-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
