# Generated by Django 4.1.2 on 2022-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='forgot_password_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
