# Generated by Django 4.1.2 on 2022-11-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
