# Generated by Django 4.1.2 on 2022-11-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_remove_category_subcategory_remove_images_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
    ]
