# Generated by Django 4.1.2 on 2022-12-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
