# Generated by Django 4.1.2 on 2022-11-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
