# Generated by Django 4.1.2 on 2022-11-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0011_remove_product_variants_subcategory_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
