# Generated by Django 4.1.2 on 2022-11-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0012_delete_variants_remove_product_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
