# Generated by Django 4.1.2 on 2022-11-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0014_subcategory_product_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
