# Generated by Django 4.1.2 on 2022-11-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0016_order_alter_product_desc_shippingaddress_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
