# Generated by Django 4.1.2 on 2022-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0021_orderitems_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='media/images/banner')),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
