# Generated by Django 4.1.2 on 2022-11-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0022_bannermanagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermanagement',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='bannermanagement',
            old_name='Description',
            new_name='name',
        ),
    ]
