# Generated by Django 4.1.2 on 2022-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0023_rename_main_image_bannermanagement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermanagement',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
