# Generated by Django 4.1.2 on 2022-11-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0024_alter_bannermanagement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_choices',
        ),
    ]
