# Generated by Django 4.1.2 on 2022-11-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0025_remove_order_payment_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='date_added',
        ),
    ]
