# Generated by Django 4.1.2 on 2022-11-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0027_productoffer_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discound_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
