# Generated by Django 4.1.2 on 2022-11-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0028_product_discound_price_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discound_price',
        ),
    ]
