# Generated by Django 4.1.2 on 2022-11-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0029_remove_product_discound_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='discound',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
