# Generated by Django 4.1.2 on 2022-11-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_remove_ordereditems_category_offer_and_more'),
        ('proj', '0031_product_product_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_off',
        ),
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
