# Generated by Django 4.1.2 on 2022-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0032_remove_productoffer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
