# Generated by Django 4.1.2 on 2022-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0033_product_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
