# Generated by Django 4.1.2 on 2022-11-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0034_category_offer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
