# Generated by Django 4.1.2 on 2022-12-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0036_orderitems_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
