# Generated by Django 4.1.2 on 2022-12-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0038_shippingaddress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
