# Generated by Django 4.1.2 on 2022-12-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0039_alter_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
