# Generated by Django 4.1.2 on 2022-11-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
