# Generated by Django 4.1.2 on 2022-12-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen', models.CharField(max_length=10)),
                ('price', models.IntegerField(default='200')),
                ('minimum_price', models.IntegerField(default='500')),
                ('maximum_price', models.IntegerField(default='5000')),
            ],
        ),
    ]
