# Generated by Django 4.1.2 on 2022-11-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='maximum_price',
            field=models.CharField(default='5000', max_length=100),
        ),
        migrations.AddField(
            model_name='coupen',
            name='minimum_price',
            field=models.CharField(default='500', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='price',
            field=models.CharField(default='200', max_length=200),
        ),
    ]
