# Generated by Django 4.1.2 on 2022-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupen', '0002_coupen_maximum_price_coupen_minimum_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='maximum_price',
            field=models.IntegerField(default='5000', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='minimum_price',
            field=models.IntegerField(default='500', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='price',
            field=models.IntegerField(default='200', max_length=200),
        ),
    ]
