# Generated by Django 4.1.2 on 2022-11-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupen', '0003_alter_coupen_maximum_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='maximum_price',
            field=models.IntegerField(default='5000'),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='minimum_price',
            field=models.IntegerField(default='500'),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='price',
            field=models.IntegerField(default='200'),
        ),
    ]
