# Generated by Django 4.1.2 on 2022-12-08 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0001_initial'),
        ('coupen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('delivered', 'delivered'), ('pending', 'pending'), ('out for shipping', 'out for shipping')], default='pending', max_length=20)),
                ('payment', models.CharField(max_length=120, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_price', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=40, null=True)),
                ('coupen_applied', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('ordered', models.DateTimeField(auto_now_add=True)),
                ('discound', models.IntegerField(blank=True, default=0, null=True)),
                ('is_return', models.BooleanField(blank=True, default=False, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coupen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupen.coupen')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.product')),
                ('shippingaddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.shippingaddress')),
            ],
        ),
    ]
