# Generated by Django 4.1.2 on 2022-11-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0019_order_payment_choices'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='product',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='orderitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.orderitems'),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='shippingaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.shippingaddress'),
        ),
    ]
