# Generated by Django 4.1.2 on 2022-11-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_ordereditems_product_ordereditems_orderitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='quantity',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
