# Generated by Django 4.1.2 on 2022-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_ordereditems_price_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='active',
            field=models.CharField(default='ordered', max_length=20),
        ),
    ]
