# Generated by Django 4.1.2 on 2022-11-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0020_shippingaddress_phone'),
        ('cart', '0006_ordereditems_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj.order'),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='orderitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj.orderitems'),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=20),
        ),
    ]
