# Generated by Django 4.1.2 on 2022-11-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0020_shippingaddress_phone'),
        ('cart', '0007_alter_ordereditems_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.product'),
        ),
    ]
