# Generated by Django 4.1.2 on 2022-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_ordereditems_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='orderitems',
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
