# Generated by Django 4.1.2 on 2022-11-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupen', '0001_initial'),
        ('cart', '0008_remove_ordereditems_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='coupen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupen.coupen'),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('out for shipping', 'out for shipping')], default='pending', max_length=20),
        ),
    ]
