# Generated by Django 4.1.2 on 2022-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_ordereditems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
