# Generated by Django 4.1.2 on 2022-11-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_ordereditems_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
