# Generated by Django 4.1.2 on 2022-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
