# Generated by Django 4.1.2 on 2022-11-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_ordereditems_coupen_applied_ordereditems_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('out for shipping', 'out for shipping')], default='pending', max_length=20),
        ),
    ]
