# Generated by Django 4.1.2 on 2022-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_ordereditems_payment_id_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='tracking_no',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='payment',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
