# Generated by Django 4.1.2 on 2022-11-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_ordereditems_message_ordereditems_tracking_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='payment',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('out for shipping', 'out for shipping')], default='pending', max_length=20),
        ),
    ]
