# Generated by Django 4.1.2 on 2022-11-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_alter_ordereditems_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='category_offer',
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='discound_price',
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='product_offer',
        ),
    ]
