# Generated by Django 4.1.2 on 2022-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='discound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
