# Generated by Django 4.1.2 on 2022-11-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='is_return',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('delivered', 'delivered'), ('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
