# Generated by Django 4.1.2 on 2022-11-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_ordereditems_is_return_ordereditems_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out for shipping', 'out for shipping'), ('delivered', 'delivered'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
