# Generated by Django 4.1.2 on 2022-12-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0042_alter_ordereditems_ordered_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('pending', 'pending'), ('completed', 'completed'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
