# Generated by Django 4.1.2 on 2022-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0045_alter_ordereditems_ordered_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('delivered', 'delivered'), ('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
