# Generated by Django 4.1.2 on 2022-12-06 05:42

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0051_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='delivered_at',
            field=cart.models.CustomDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out for shipping', 'out for shipping'), ('completed', 'completed'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
