# Generated by Django 4.1.2 on 2022-12-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0053_alter_ordereditems_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('delivered', 'delivered'), ('out for shipping', 'out for shipping'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
