# Generated by Django 4.1.2 on 2022-12-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0054_ordereditems_return_date_alter_ordereditems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('completed', 'completed'), ('pending', 'pending'), ('out for shipping', 'out for shipping')], default='pending', max_length=20),
        ),
    ]
